version: "3"

services:
  chall:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:2000
    networks:
      net:
  
  health:
    build:
      context: .
      dockerfile: Healthcheck.dockerfile
    networks:
      net:
    healthcheck:
      test: ["CMD", "/home/health/health.py", "REMOTE"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 5

networks:
  net:
